### ISSUE TITLE
/sdcard links to the root directory

### ISSUE THREAD

**Issue by jonalmeida** [zach-klippenstein/adbfs#14]
After a successful mount, the `sdcard` directory gets wrongly linked to the root directory, so opening it shows you the root directory again.

Platform-tools - 23.1 rc1
ADB - 1.0.32
SDK Build-tools - 23.0.1

See screenshot below:

<img width="998" alt="screen shot 2015-11-30 at 21 35 19" src="https://cloud.githubusercontent.com/assets/1370580/11490829/4fe5b122-97aa-11e5-9a93-f23633f56b78.png">

**Comment by zach-klippenstein** [comment]
Thanks for reporting! What device did you observe this on?

**Comment by jonalmeida** [comment]
Oops forgot to mention that.

Nexus 5, Android 6.0 (MRA58N)

**Comment by zach-klippenstein** [comment]
So the `readlink` shell command seems to be returning an empty string. Running `readlink` manually using `adb shell` works, so maybe something about the protocol changed. Still investigating.

**Comment by zach-klippenstein** [comment]
Figured it out: the `readlink` command seems to have changed in Marshmallow. Its usage text still shows it supports the `-f` argument, but when called with that argument it doesn't print anything and exits with exit code 1.

I think the best solution is to stop trying to resolve symlinks recursively on device.
