### ISSUE TITLE
Build SHA not set

### ISSUE THREAD

**Issue by voidzero** [zach-klippenstein/adbfs#16]
Hi, I'm trying adbfs, but launching it fails with the following error (same for the adbfs binary):

<pre>% ./go.sh run cmd/adbfs/main.go ~/user/mnt
+ go run -ldflags '-X github.com/zach-klippenstein/adbfs/internal/cli.buildSHA=23ff9c5' cmd/adbfs/main.go /home/voidzero/user/mnt
panic: build SHA not set

goroutine 1 [running]:
github.com/zach-klippenstein/adbfs/internal/cli.BuildSHA(0x0, 0x0)
        /home/voidzero/user/go/src/github.com/zach-klippenstein/adbfs/internal/cli/cli.go:33 +0x83
github.com/zach-klippenstein/adbfs/internal/cli.versionString(0x93e480, 0x5, 0x0, 0x0)
        /home/voidzero/user/go/src/github.com/zach-klippenstein/adbfs/internal/cli/cli.go:50 +0x31
github.com/zach-klippenstein/adbfs/internal/cli.Initialize(0x93e480, 0x5, 0xbe32a0)
        /home/voidzero/user/go/src/github.com/zach-klippenstein/adbfs/internal/cli/cli.go:25 +0x84
main.main()
        /home/voidzero/user/go/src/github.com/zach-klippenstein/adbfs/cmd/adbfs/main.go:48 +0x4b

goroutine 9 [runnable]:
text/template/parse.lexText(0xc20807d180, 0xa3b040)
        /usr/lib/go/src/text/template/parse/lex.go:228 +0x37b
text/template/parse.(*lexer).run(0xc20807d180)
        /usr/lib/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
        /usr/lib/go/src/text/template/parse/lex.go:191 +0x1ac

goroutine 8 [syscall]:
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/lib/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1
exit status 2
</pre>

**Comment by zach-klippenstein** [comment]
I'm not seeing this with go 1.5.1. Do you see the same error if you run the command directly? I.e.

```
go run -ldflags '-X github.com/zach-klippenstein/adbfs/internal/cli.buildSHA=23ff9c5' cmd/adbfs/main.go
```

**Comment by voidzero** [comment]
I'm trying this with Go 1.4.2. I'll update to 1.5.1 and let you know.

**Comment by zach-klippenstein** [comment]
There's another issue where someone is installing with 1.4.2 on darwin/amd64 without this issue, so I don't think go version is the problem. What shell and OS are you using? Also still curious what happens if you run that `go run` command directly.

**Comment by voidzero** [comment]
The output:

<pre>% go run -ldflags '-X github.com/zach-klippenstein/adbfs/internal/cli.buildSHA=23ff9c5' cmd/adbfs/main.go
panic: build SHA not set

goroutine 1 [running]:
github.com/zach-klippenstein/adbfs/internal/cli.BuildSHA(0x0, 0x0)
        /home/voidzero/user/go/src/github.com/zach-klippenstein/adbfs/internal/cli/cli.go:33 +0x83
github.com/zach-klippenstein/adbfs/internal/cli.versionString(0x93e480, 0x5, 0x0, 0x0)
        /home/voidzero/user/go/src/github.com/zach-klippenstein/adbfs/internal/cli/cli.go:50 +0x31
github.com/zach-klippenstein/adbfs/internal/cli.Initialize(0x93e480, 0x5, 0xbe32a0)
        /home/voidzero/user/go/src/github.com/zach-klippenstein/adbfs/internal/cli/cli.go:25 +0x84
main.main()
        /home/voidzero/user/go/src/github.com/zach-klippenstein/adbfs/cmd/adbfs/main.go:48 +0x4b

goroutine 9 [runnable]:
text/template/parse.lexText(0xc20807d180, 0xa3b040)
        /usr/lib/go/src/text/template/parse/lex.go:228 +0x37b
text/template/parse.(*lexer).run(0xc20807d180)
        /usr/lib/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
        /usr/lib/go/src/text/template/parse/lex.go:191 +0x1ac

goroutine 8 [syscall]:
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/lib/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1
exit status 2
</pre>

This is a Funtoo Hardened system, amd64, very similar to Gentoo. Go version 1.4.2. I'll try 1.5.1 after the holidays. Tnx so far :+1:

**Comment by zach-klippenstein** [comment]
I haven't tried building on anything other than OSX, I'll set up a vm and see if I can repro.

**Comment by zach-klippenstein** [comment]
Just ran the install script on an amd64 Debian system with go 1.5.2, it worked fine. Was the package imported in a weird way? I.e. Does `$GOPATH/src/github.com/zach-klippenstein/adbfs/internal/cli` exist?

**Comment by voidzero** [comment]
That path does exist, yes.

I'm not familiar with Go so it's not easy for me to debug, but the way I added it following the readme's instructions was, first I ran `go get github.com/zach-klippenstein/adbfs`. Then, when I executed `./install.sh` I got a dependency error. So I ran `gopkg.in/alecthomas/kingpin.v2`. Then I ran `install.sh` again and that's when the above issue occurred... hope this is helpful info.

**Comment by zach-klippenstein** [comment]
From what you've said everything should work, I have no idea why you're getting this error. Have you had any weird errors with other go packages? I've been thinking the build sha stuff is probably unnecessary anyway. Pull from master run the install script again. The build sha error should be gone, but if something that simple was broken on your system there might be more other weird errors.
