### ISSUE TITLE
Install issue on OSX - cannot find package "gopkg.in/alecthomas/kingpin.v2"

### ISSUE THREAD

**Issue by jfrumar** [zach-klippenstein/adbfs#17]
Installing on OSX, I received this output when running the `go get` command:

```# github.com/hanwen/go-fuse/fuse/nodefs
golang/src/github.com/hanwen/go-fuse/fuse/nodefs/files_darwin.go:5: imported and not used: "time"
golang/src/github.com/hanwen/go-fuse/fuse/nodefs/syscall.go:11: undefined: syscall.SYS_UTIMENSAT```

Then when running ./install.sh I received:

```+ go install -ldflags '-X github.com/zach-klippenstein/adbfs/internal/cli.buildSHA=23ff9c5' -v ./cmd/...
internal/cli/adbfs_config.go:3:8: cannot find package "gopkg.in/alecthomas/kingpin.v2" in any of:
	/usr/local/Cellar/go/1.5.2/libexec/src/gopkg.in/alecthomas/kingpin.v2 (from $GOROOT)
	/Users/jules/Downloads/golang/src/gopkg.in/alecthomas/kingpin.v2 (from $GOPATH)```

**Comment by jfrumar** [comment]
Suggestion: would be awesome if this package was added to [Homebrew](http://brew.sh/). Then mac users go do `brew install adbfs`

**Comment by unformatt** [comment]
See https://github.com/zach-klippenstein/adbfs/issues/12

**Comment by jfrumar** [comment]
I got it installed - I recommend adding `GO15VENDOREXPERIMENT=1` to the installation instructions

**Comment by zach-klippenstein** [comment]
@jfrumar I looked at adding it to Homebrew, but the [Acceptable Formulae](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#niche-or-self-submitted-stuff) doc requires that packages be "known", "used", and "stable" – none of which describe this project at this point (although an argument could now be made for the first two). 

I'll add the vendoring experiment to the instructions.

**Comment by jfrumar** [comment]
Cool fair enough - look forwards to the future then! :)

On Thu, Dec 24, 2015 at 4:33 AM, Zach Klippenstein <notifications@github.com
