### ISSUE TITLE
Implement writes

### ISSUE THREAD

**Issue by jfrumar** [zach-klippenstein/adbfs#18]
I'm successfully mounting emulators on mac, but I can't seem to write to them. I'm attempting to write to the /sdcard dir, and receiving:

```jules@Juless-MacBook-Pro ~/mnt/Google_Nexus_5_5_1_0_API_22_1080x1920_updated-192_168_57_101_5555/sdcard $ touch foo.text
touch: foo.text: Function not implemented```

Is writing unimplemented yet?

**Comment by zach-klippenstein** [comment]
Yep, writing hasn't been implemented yet.

**Comment by jfrumar** [comment]
Is it coming soon? I'd recommend mentioning this in the README (I spent a
chunk of time building adbfs into our toolset without awareness that it
wouldn't be functional yet).

On Thu, Dec 24, 2015 at 4:28 AM, Zach Klippenstein <notifications@github.com

**Comment by zach-klippenstein** [comment]
For writing, in addition to supporting file writes, the following operations will be supported (from https://godoc.org/github.com/hanwen/go-fuse/fuse/pathfs#FileSystem):

* Create
* Chmod
* Chown
* Utimens
* Mkdir
* Rmdir
* Rename
* Link
* Unlink
* Symlink

**Comment by jfrumar** [comment]
This sounds great! I just need to create dirs and files.

I just checked out the latest and re-ran the install.sh script. Automounter is mounting a Genymotion emulator, but the contents of the dir are empty.

**Comment by zach-klippenstein** [comment]
Can you run automounter with the `-v` flag and send me the output? 

In other news, I've got support for file writes kind of working in a branch for OSX, but Finder's doing some weird stuff so you have to use the command line for most things. If you want to give it a try checkout the file-write branch.

**Comment by jfrumar** [comment]
Awesome to see your rapid progress here - thanks!

I have been having some issues with Genymotion since the last update (super slow, and locks up). So I'm using the Android emulator at the moment. The auto-mounter successfully mounted the FS, and I can create folders now! When I try to copy files via finder, I get a "..can't be copied because there isn't enough space" message.

**Comment by zach-klippenstein** [comment]
Yea, Finder doesn't seem to think it can write, and some other apps (namely Preview). I've had better luck with things that don't try to do a bunch of fancy metadata/versioning stuff (command line, Sublime Text). I think the Finder problem might have to do with resource forks, but adbfs isn't showing any errors, just that Finder opens and closes the `._*` files a bunch and occasionally writes to them.

**Comment by zach-klippenstein** [comment]
Still haven't been able to find out why Finder doesn't want to cooperate. The file-write branch is getting a lot closer to being ready to merge though, I basically just need to write a bunch of tests and make sure I haven't broken anything with all the rebasing I've been doing this week. I'm back to my day job this week though so not sure when I'll get to finishing it.

**Comment by zach-klippenstein** [comment]
Finder bug is now its own issue: #34
