### ISSUE TITLE
Allow specifying the path of device to be mounted

### ISSUE THREAD

**Issue by saeidscorp** [zach-klippenstein/adbfs#45]
Hi, and thanks for this awesome piece of software! (especially with failures of libmtp)

However, the mounter only mounts the /sdcard on the device. I need to access both internal & external sd cards of my phone. (residing in /storage)
I didn't see any options for specifying that.

Is it supported by any tricks?! (other than rooting the device, of course)

**Comment by zach-klippenstein** [comment]
Sounds like you're looking for the `--device-root` flag:

```
adbfs --help
usage: adbfs --device=DEVICE --mountpoint=/mnt [<flags>]

Flags:
  -h, --help                   Show context-sensitive help (also try --help-long and --help-man).
  …
      --device-root="/sdcard"  The device directory to mount.
  …
      --mountpoint=/mnt        Directory to mount the device on.
      --version                Show application version.
```
